import { Braces, CaseSensitive, Clock3, Code2, Diff, FileCode2, FileText, Fingerprint, Hash, ImageDown, KeyRound, Link, Palette, QrCode, Regex, Sparkles, Type, WholeWord } from "lucide-react";
import type { LucideIcon } from "lucide-react";
export type ToolId = "json" | "base64" | "url" | "regex" | "hash" | "uuid" | "html" | "diff" | "word" | "case" | "lorem" | "markdown" | "color" | "gradient" | "password" | "timestamp" | "qr" | "image";
export type ToolCategory = "Development" | "Text" | "Design" | "Security" | "Media";
export type ToolMeta = { id: ToolId; name: string; description: string; category: ToolCategory; icon: LucideIcon };
export const tools: ToolMeta[] = [
  { id:"json",name:"JSON Formatter",description:"Beautify, minify, and validate JSON",category:"Development",icon:Braces }, { id:"base64",name:"Base64 Tool",description:"Encode and decode Base64 text",category:"Development",icon:Code2 }, { id:"url",name:"URL Encoder",description:"Encode and decode URL components",category:"Development",icon:Link }, { id:"regex",name:"Regex Tester",description:"Test patterns against text in real time",category:"Development",icon:Regex }, { id:"hash",name:"Hash Generator",description:"Generate MD5 and SHA hashes",category:"Security",icon:Hash }, { id:"uuid",name:"UUID Generator",description:"Create RFC 4122 version 4 UUIDs",category:"Development",icon:Fingerprint }, { id:"html",name:"HTML Escape",description:"Escape and unescape HTML entities",category:"Text",icon:FileCode2 }, { id:"diff",name:"Diff Checker",description:"Compare two text documents",category:"Development",icon:Diff }, { id:"word",name:"Word Counter",description:"Count words, characters, and more",category:"Text",icon:WholeWord }, { id:"case",name:"Case Converter",description:"Transform text between common cases",category:"Text",icon:CaseSensitive }, { id:"lorem",name:"Lorem Ipsum",description:"Generate placeholder copy",category:"Text",icon:Type }, { id:"markdown",name:"Markdown Preview",description:"Write Markdown with live preview",category:"Text",icon:FileText }, { id:"color",name:"Color Picker",description:"Convert HEX, RGB, and HSL colors",category:"Design",icon:Palette }, { id:"gradient",name:"CSS Gradient",description:"Create polished CSS gradients",category:"Design",icon:Sparkles }, { id:"password",name:"Password Generator",description:"Generate secure passwords",category:"Security",icon:KeyRound }, { id:"timestamp",name:"Timestamp Converter",description:"Convert Unix timestamps and dates",category:"Development",icon:Clock3 }, { id:"qr",name:"QR Generator",description:"Make downloadable QR codes",category:"Design",icon:QrCode }, { id:"image",name:"Image Compressor",description:"Compress images in your browser",category:"Media",icon:ImageDown }
];
export const categories: ToolCategory[] = ["Development","Text","Design","Security","Media"];
